### ISSUE TITLE
Unable to load lottie file.

### ISSUE THREAD

**Issue by FG-rgb** [LottieFiles/dotlottie-cs#15]
## Overview

...

## Consuming repo

> What repo were you working in when this issue occurred?

Using dotlottie-cs NuGet Package.

## Labels

Hello, I've converted my lottie json file to "file.lottie" via the online converter.
Now I'm loading the file with following code:

```
var assembly = Assembly.GetExecutingAssembly();
var resource = assembly.GetManifestResourceStream("LottieNet.Gears.lottie");
var lottie = await DotLottie.OpenAsync(resource);
```

The OpenAsync call now throws following exception:

System.NotSupportedException: Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'LottieFiles.IO.Manifest'. Path: $ | LineNumber: 0 | BytePositionInLine: 1. ---> System.NotSupportedException: Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'LottieFiles.IO.Manifest'.
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Text.Json.ThrowHelper.ThrowNotSupportedException(ReadStack& state, Utf8JsonReader& reader, NotSupportedException ex)
   bei System.Text.Json.ThrowHelper.ThrowNotSupportedException_DeserializeNoConstructor(Type type, Utf8JsonReader& reader, ReadStack& state)
   bei System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   bei System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   bei System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   bei System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   bei System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   bei System.Text.Json.JsonSerializer.<ReadAsync>d__20`1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei LottieFiles.IO.DotLottie.<OpenAsync>d__14.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei LottieNet.MainWindow.<MainWindow_ContentRendered>d__1.MoveNext() in C:\Work\LottieNet\LottieNet\MainWindow.xaml.cs:Zeile 33.

What's the problem here?

**Comment by alex-harper** [comment]
Thanks for reporting this - if you're able to share the lottie with me, I'll take a look.

**Comment by FG-rgb** [comment]
Hello,

I've deleted but, but I re-convertered my json.
Github does not support lottie and json file format.
Therefore I've zipped it.


[Gears.zip](https://github.com/LottieFiles/dotlottie-cs/files/6636360/Gears.zip)

**Comment by alex-harper** [comment]
Hi,

Thanks for sending that over. I included it in a test project locally and was able to replicate the issue if I changed to dotnet5, it seems it's down to a breaking change between dotnet core 3.1 and dotnet 5:

https://docs.microsoft.com/en-us/dotnet/core/compatibility/serialization/5.0/non-public-parameterless-constructors-not-used-for-deserialization

I can take a look at this today and get a new version out that's dotnet 5 compatible, thanks for reporting the issue!

**Comment by FG-rgb** [comment]
Thank you, too.

Have a nice day ;)

**Comment by alex-harper** [comment]
Hey, new version is out and it should be compatible now. Thanks once again!
